# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Description
  description: Description of club
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background: grey
  heading: bookshop:generic/heading
  content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: bookshop:generic/heading
  content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero fugiat
    cum ad officia, harum, et voluptas quia vel voluptatem aliquam, facilis
    corporis nam tempore ullam doloribus iusto sequi ipsum. Fugiat non culpa ad
    beatae sed dolorem doloribus accusamus
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background:
    type: select
    options:
      values:
        - grey
        - black
