title: 'Raconteurs d''Angles'
default_lang: fr
author:
  name: 'Raconteurs d''Angles'
  email: theatre@etsmtl.ca
taxonomies:
  - category
  - tag
metadata: null
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
